#include "cuda_shuffle_nonshared.h"
#include "types.h"
#include <cuda_runtime_api.h>
#include <stdio.h>

// Each thread computes one output element C[row][col].
// Threads are arranged as a 2D block: x=cols, y=rows.
// Within each warp (32 threads along x), B values are rotated
// via __shfl_sync so each thread accumulates its full dot product
// without any shared memory.
//
// Generated by Claude Sonnet
#define WARP_SIZE 32
#define BLOCK_ROWS 16        // threadDim.y — rows per block
#define BLOCK_COLS WARP_SIZE // threadDim.x — must be WARP_SIZE

__global__ void _warp_shuffle_nonshared(const float *A, const float *B,
                                        float *C, int m, int k, int n) {
  const int lane = threadIdx.x;
  const int ty = threadIdx.y;

  const int globalRow = blockIdx.y * BLOCK_ROWS + ty;
  const int globalCol = blockIdx.x * WARP_SIZE + lane;

  if (globalRow >= m)
    return;

  const unsigned int FULL_MASK = 0xffffffffu;

  float acc = 0.0f;

  for (int kt = 0; kt < k; kt += WARP_SIZE) {

    // Each lane loads one A value from its row.
    // Lane l loads A[globalRow][kt+l].
    int aCol = kt + lane;
    float myA = (aCol < k) ? A[globalRow * k + aCol] : 0.0f;

    // At step s, each thread needs:
    //   A[globalRow][kt+s] * B[kt+s][globalCol]
    //
    // A[globalRow][kt+s] is held by lane s — broadcast it to all lanes.
    // B[kt+s][globalCol] is loaded directly by each thread for its own column.
    // This keeps the shuffle strictly unidirectional (always reading from lane
    // s).
    for (int s = 0; s < WARP_SIZE; ++s) {
      // Broadcast A[globalRow][kt+s] from lane s to all lanes
      float a = __shfl_sync(FULL_MASK, myA, s);

      // Each thread loads its own B value directly from global memory
      int bRow = kt + s;
      float b = (bRow < k && globalCol < n) ? B[bRow * n + globalCol] : 0.0f;

      acc += a * b;
    }
  }

  if (globalCol < n)
    C[globalRow * n + globalCol] = acc;
}

void multiply_warp_shuffle_nonshared(const float *A, const float *B, float *C,
                                     int m, int k, int n, kernel_args_t *args) {
  dim3 block(BLOCK_COLS, BLOCK_ROWS);
  dim3 grid((n + WARP_SIZE - 1) / WARP_SIZE, (m + BLOCK_ROWS - 1) / BLOCK_ROWS);

  _warp_shuffle_nonshared<<<grid, block>>>(A, B, C, m, k, n);

  cudaError_t err = cudaGetLastError();
  if (err != cudaSuccess)
    printf("_warp_shuffle_nonshared launch error: %s\n",
           cudaGetErrorString(err));
}
